-- ちりつも単語 フレンド機能: スキーマ（相乗り版・全て wq_ 接頭辞）
--
-- 既存の Supabase プロジェクト（ラッキーセブン／PawPlanet が同居）に相乗りする。
-- テーブル・関数・インデックスを全て wq_ 接頭辞にして、既存アプリと衝突しない。
-- Supabase の SQL Editor で「wq_01_schema.sql → wq_02_functions.sql」の順に実行する。
-- 既存データには一切触れない（create if not exists のみ。drop は行わない）。
--
-- 設計方針（PawPlanet の paw_ と同じ）:
--   - 基盤テーブルへの直接 SELECT は「自分の行だけ」（RLS）
--   - 他人の行の読み取りは SECURITY DEFINER の RPC 経由のみ
--   - 書き込みは本人の行のみ

-- ============================================================
-- wq_profiles: 自分の公開スナップショット（本人が upsert）
-- ============================================================
create table if not exists public.wq_profiles (
    id              uuid primary key references auth.users (id) on delete cascade,
    display_name    text not null check (char_length(display_name) between 1 and 12),
    friend_code     text unique not null check (friend_code ~ '^[2-9A-HJ-NP-Z]{8}$'),
    -- フレンドランキングの2軸
    streak          int  not null default 0 check (streak >= 0),
    weekly_words    int  not null default 0 check (weekly_words >= 0),
    -- 「今日まだ学習していない友達」の判定に使う
    last_study_date date,
    -- その人が今学んでいる言語（表示用。ランキングは合算なので絞り込みには使わない）
    category        text not null default 'english' check (char_length(category) <= 20),
    updated_at      timestamptz not null default now()
);

alter table public.wq_profiles enable row level security;

create policy "wq_profiles_select_own" on public.wq_profiles
    for select using (auth.uid() = id);
create policy "wq_profiles_insert_own" on public.wq_profiles
    for insert with check (auth.uid() = id);
create policy "wq_profiles_update_own" on public.wq_profiles
    for update using (auth.uid() = id) with check (auth.uid() = id);

-- ============================================================
-- wq_friendships: 友達関係（双方向に2行入れる）
-- ============================================================
create table if not exists public.wq_friendships (
    user_id    uuid not null references auth.users (id) on delete cascade,
    friend_id  uuid not null references auth.users (id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, friend_id),
    constraint wq_friendships_not_self check (user_id <> friend_id)
);

create index if not exists wq_friendships_user_idx on public.wq_friendships (user_id);

alter table public.wq_friendships enable row level security;

create policy "wq_friendships_select_own" on public.wq_friendships
    for select using (auth.uid() = user_id);
-- 追加・削除は RPC（SECURITY DEFINER）経由のみ。双方向の整合を関数側で担保する。

-- ============================================================
-- wq_nudges: つつき（1日1回）
-- ============================================================
create table if not exists public.wq_nudges (
    id         bigint generated by default as identity primary key,
    from_id    uuid not null references auth.users (id) on delete cascade,
    to_id      uuid not null references auth.users (id) on delete cascade,
    -- ローカル日付（YYYY-MM-DD）。1日1回の制約はこの列で効かせる
    nudge_day  date not null,
    claimed    boolean not null default false,
    created_at timestamptz not null default now(),
    constraint wq_nudges_not_self check (from_id <> to_id),
    -- 同じ相手を同じ日に二度つつけない
    constraint wq_nudges_once_a_day unique (from_id, to_id, nudge_day)
);

create index if not exists wq_nudges_to_unclaimed_idx
    on public.wq_nudges (to_id) where claimed = false;

alter table public.wq_nudges enable row level security;

create policy "wq_nudges_select_mine" on public.wq_nudges
    for select using (auth.uid() = to_id or auth.uid() = from_id);
-- 送信・受取は RPC 経由のみ。
